Add Keycloak support
trilbymedia/grav-plugin-login-oauth2-extras pull request #5
Opened 2021-12-19 15:44 UTC by andreasgrill

Add support for Keycloak instances through the Keycloak OAuth provider
https://github.com/stevenmaguire/oauth2-keycloak.

2021-12-22 18:31 UTC, an-ant0ni0 requested changes

2021-12-22 18:31 UTC, an-ant0ni0 commented on README.md
> +    authserverl_url: ''
```suggestion
    authserver_url: ''
```

2021-12-22 18:31 UTC, an-ant0ni0 commented on README.md
> +      authserverl_url: ''
```suggestion
      authserver_url: ''
```

2022-02-28 18:58 UTC, merged

2022-02-28 18:59 UTC, rhukster commented
I manually merged this.  thanks!

2022-02-28 19:39 UTC, rhukster commented
BTW, please test this as I had to manually merge and didn't test it.

2022-03-16 16:10 UTC, andreasgrill commented
Thanks for merging! 
I've tested the changes from the develop branch with our Keycloak instance and it still works.

2022-03-16 17:57 UTC, rhukster commented
Ok thanks! going to release.